export const COUNTRY_CODE = {
	ABW: "Aruba",
	AFG: "Afganistan",
	AGO: "Angola",
	AIA: "Anguila",
	ALA: "Aland Islands",
	ALB: "Albania",
	AND: "Andorra",
	DZA: "Argelia",
	ASM: "American Samoa",
	ATA: "Antarctica",
	ATG: "Antigua and Barbuda",
	ARG: "Argentina",
	AUS: "Australia",
	AUT: "Austria",
	AZE: "Azerbaiyan",
	BHS: "Bahamas",
	BHR: "Barein",
	BGD: "Bangladesh",
	BRB: "Barbados",
	BLR: "Bielorrusia",
	BEL: "Belgium",
	BLZ: "Belice",
	BEN: "Benín",
	BMU: "Bermuda",
	BTN: "Bután",
	BOL: "Bolivia",
	BES: "Bonaire, Sint Eustatius and Saba",
	BIH: "Bosnia and Herzegovina",
	BWA: "Botsuana",
	BVT: "Bouvet Island",
	BRA: "Brazil",
	IOT: "British Indian Ocean Territory",
	VGB: "Virgin Islands (British)",
	BRN: "Brunei",
	BGR: "Bulgaria",
	BFA: "Burkina Faso",
	BDI: "Burundi",
	KHM: "Camboya",
	CMR: "Camerún",
	CAN: "Canada",
	CPV: "Cabo Verde",
	CYM: "Cayman Islands",
	CAF: "Central African Republic",
	TCD: "Chad",
	CHL: "Chile",
	CHN: "China",
	CXR: "Christmas Island",
	CCK: "Cocos Island",
	COL: "Colombia",
	COM: "Comoras",
	COK: "Cook Islands",
	CRI: "Costa Rica",
	HRV: "Croacia",
	CUB: "Cuba",
	CUW: "Curazao",
	CYP: "Chipre",
	CZE: "Czechia",
	COD: "Congo",
	DNK: "Dinamarca",
	DJI: "Yibuti",
	DMA: "Dominica",
	DOM: "Dominican Republic",
	TLS: "Timor-Leste",
	ECU: "Ecuador",
	EGY: "Egipto",
	SLV: "El Salvador",
	GNQ: "Guinea Ecuatorial",
	ERI: "Eritrea",
	EST: "Estonia",
	ETH: "Etiopía",
	FLK: "Falkland Islands",
	FRO: "Faroe Islands",
	FJI: "Fiji",
	FIN: "Finlandia",
	FRA: "France",
	GUF: "French Guiana",
	PYF: "French Polynesia",
	ATF: "French Southern Territories",
	GAB: "Gabón",
	GMB: "Gambia",
	GEO: "Georgia",
	DEU: "Germany",
	GHA: "Ghana",
	GIB: "Gibraltar",
	GRC: "Grecia",
	GRL: "Groenlandia",
	GRD: "Granada",
	GLP: "Guadalupe",
	GUM: "Guam",
	GTM: "Guatemala",
	GGY: "Guernsey",
	GIN: "Guinea",
	GNB: "Guinea Bissau",
	GUY: "Guyana",
	HTI: "Haití",
	HMD: "Islas Heard and Mcdonald",
	HND: "Honduras",
	HKG: "Hong Kong",
	HUN: "Hungary",
	ISL: "Iceland",
	IND: "India",
	IDN: "Indonesia",
	IRN: "Iran",
	IRQ: "Irak",
	IRL: "Irlanda",
	IMN: "Isle of Man",
	ISR: "Israel",
	ITA: "Italia",
	CIV: "Côte d'Ivoire",
	JAM: "Jamaica",
	JPN: "Japan",
	JEY: "Jersey",
	JOR: "Jordania",
	KAZ: "Kazajistan",
	KEN: "Kenia",
	KIR: "Kiribati",
	XXK: "Kosovo",
	KWT: "Kuwuait",
	KGZ: "Kirguistán",
	LAO: "Laos",
	LVA: "Letonia",
	LBN: "Lebanon",
	LSO: "Lesoto",
	LBR: "Liberia",
	LBY: "Libia",
	LIE: "Leichtenstein",
	LTU: "Lithuania",
	LUX: "Luxembourg",
	MAC: "Macao",
	MKD: "Macedonia",
	MDG: "Madagascar",
	MWI: "Malaui",
	MYS: "Malasia",
	MDV: "Maldivas",
	MLI: "Mali",
	MLT: "Malta",
	MHL: "Marshall Islands",
	MTQ: "Martinica",
	MRT: "Mauritania",
	MUS: "Mauricio",
	MYT: "Mayotte",
	MEX: "Mexico",
	FSM: "Micronesia",
	MDA: "Moldavia",
	MCO: "Monaco",
	MNG: "Mongolia",
	MNE: "Montenegro",
	MSR: "Montserrat",
	MOZ: "Mozambique",
	MMR: "Myanmar",
	NAM: "Namibia",
	NRU: "Nauru",
	NPL: "Nepal",
	NLD: "Netherlands",
	ANT: "Antillas Holandesas",
	NCL: "New Caledonia",
	NZL: "New Zealand",
	NIC: "Nicaragua",
	NER: "Niger",
	NGA: "Nigeria",
	NIU: "Niue",
	NFK: "Isla Norfolk",
	PRK: "Korea",
	MNP: "Northern Mariana Islands",
	NOR: "Norway",
	OMN: "Oman",
	PAK: "Pakistan",
	PLW: "Palaos",
	PSE: "Palestine, State of",
	PAN: "Panama",
	PNG: "Papua New Guinea",
	PRY: "Paraguay",
	PER: "Peru",
	PHL: "Filipinas",
	PCN: "Pitcairn",
	POL: "Poland",
	PRT: "Portugal",
	PRI: "Puerto Rico",
	QAT: "Catar",
	COG: "Congo",
	REU: "Réunion",
	ROU: "Romania",
	RUS: "Rusia",
	RWA: "Ruanda",
	BLM: "Saint Barthélemy",
	SHN: "Saint Helena",
	KNA: "Saint Kitts and Nevis",
	LCA: "Saint Lucia",
	MAF: "Saint Martin",
	SPM: "Saint Pierre and Miquelon",
	VCT: "Saint Vincent and the Grenadines",
	WSM: "Samoa",
	SMR: "San Marino",
	STP: "Sao Tome and Principe",
	SAU: "Saudi Arabia",
	SEN: "Senegal",
	SRB: "Serbia",
	SCG: "Serbia y Montenegro",
	SYC: "Seychelles",
	SLE: "Sierra Leone",
	SGP: "Singapur",
	SXM: "Sint Maarten",
	SVK: "Eslovaquia",
	SVN: "Eslovenia",
	SLB: "Solomon Islands",
	SOM: "Somalia",
	ZAF: "Sudáfrica",
	SGS: "South Georgia and the South Sandwich Islands",
	KOR: "South Korea",
	SSD: "South Sudan",
	ESP: "Spain",
	LKA: "Sri Lanka",
	SDN: "Sudan",
	SUR: "Surinam",
	SJM: "Svalbard and Jan Mayen",
	SWZ: "Sauzilandia",
	SWE: "Sweden",
	CHE: "Switzerland",
	SYR: "Siria",
	TWN: "Taiwan",
	TJK: "Tayikistan",
	TZA: "Tanzania",
	THA: "Tailandia",
	TGO: "Togo",
	TKL: "Tokelau",
	TON: "Tonga",
	TTO: "Trinidad and Tobago",
	TUN: "Túnez",
	TUR: "Turquia",
	TKM: "Turkmenistan",
	TCA: "Turks and Caicos Islands",
	TUV: "Tuvalu",
	VIR: "Virgin Islands",
	UGA: "Uganda",
	UKR: "Ucrania",
	ARE: "United Arab Emirates",
	GBR: "United Kingdom",
	USA: "United States of America",
	UMI: "United States Minor Outlying Islands",
	URY: "Uruguay",
	UZB: "Uzbekistan",
	VUT: "Vanuatsu",
	VAT: "Vaticano",
	VEN: "Venezuela",
	VNM: "Vietnam",
	WLF: "Wallis and Futuna",
	ESH: "Western Sahara",
	YEM: "Yemen",
	ZMB: "Zambia",
	ZWE: "Zimbabue",
}

export const findCountry = (country) => {
	const result = COUNTRY_CODE[country]
	return result
}
